### ISSUE TITLE
Question: trailpack event "on" and "once"

### ISSUE THREAD

**Issue by crash83k** [trailsjs/trailpack#36]
https://github.com/trailsjs/trailpack/blob/master/index.js#L99

I noticed on this line for the `on()` method, it's using `this.app.once.apply()`. Would this prevent subsequent events from triggering? What's the difference between the `on()` method and `once()` method?

**Comment by konstantinzolotarev** [comment]
@crash83k I think it's just a typo

**Comment by crash83k** [comment]
Ok. Great. ;)

**Comment by catrielmuller** [comment]
@crash83k the diference is the fuction "on" execute the callback everytime the event is fired, and "once" only execute the callback one time, the subsequent events fired will be ignored.
Example:
```
on('init', cb)
init -> cb
init -> cb
init -> cb
```

```
once('init', cb)
init->cb
init->
init->
init->
```

**Comment by tjwebb** [comment]
Fixed in https://github.com/trailsjs/trailpack/commit/b05e6669ce4879e7657515fe083e7a833be4dd7f
