### ISSUE TITLE
Publish latest version to npm

### ISSUE THREAD

**Issue by rubenmoya** [trailsjs/trailpack#45]
Hello!

I've realised that we have the version `2.1.0` in NPM which uses `eslint@2.5`, and it's giving me this error: `1:1 error Definition for rule 'no-global-assign' was not found no-global-assign`

It's reported here already: https://github.com/trailsjs/eslint-config-trails/issues/17

I think this would fix it.

Thank you!

UPDATE: Nevermind, there are a lots of packages with `eslint@2` so probably this won't fix it, although any help will be appreciated, I could submit a PR if needed :)

**Comment by konstantinzolotarev** [comment]
@rubenmoya Same issue as in https://github.com/trailsjs/generator-trails/issues/74
